#Data Type

In [8]:
import numpy as np
#Scalar
S = 10
print("Type of S", type(S))

#Vector
V =  np.array([1,2,3,4])
print("Type of V", type(V),"Dimention of V", V.shape)

#Metrix
M = np.array([[1,2,3,4],[5,6,7,8]])
print("Type of M", type(M),"Dimention of M", M.shape)

#Tensor
T = np.array([  [[1,2,3],[4,5,6],[0,0,0]],
             [[7,8,9],[10,11,12],[13,14,15]],
             [[16,17,18],[19,20,21],[23,24,25]]
              ])
print("Type of T", type(T),"Dimention of T", T.shape)

Type of S <class 'int'>
Type of V <class 'numpy.ndarray'> Dimention of V (4,)
Type of M <class 'numpy.ndarray'> Dimention of M (2, 4)
Type of T <class 'numpy.ndarray'> Dimention of T (3, 3, 3)


# Numpy Python

In [9]:
import numpy as np

np.array([False, 42, "Data Science"])

array(['False', '42', 'Data Science'], dtype='<U21')

In [10]:
np.array([True, 42, 53.99], dtype = int)

array([ 1, 42, 53])

In [11]:
np.array([False, 42, 53.99], dtype = float)   # vector

array([ 0.  , 42.  , 53.99])

In [12]:
numbers = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(numbers[2, 1]) # 8
print(numbers[-1, 0]) #10


print(numbers[0])
print(numbers[:, 0])
print(numbers[0:3, 2] )
print(numbers[1:3, 1:3])
print(numbers[:,1])

8
10
[1 2 3]
[ 1  4  7 10]
[3 6 9]
[[5 6]
 [8 9]]
[ 2  5  8 11]

In [13]:
print(np.array([37, 48, 50]) + 10 )
print(np.array([20, 30, 40]) * 2)
print(np.array([42, 10, 60]) / 2 )

print(np.array([1, 2, 3]) * np.array([10, 20, 30]) )
print(np.array([1, 2, 3]) - np.array([10, 20, 30]) )

[47 58 60]
[40 60 80]
[21.  5. 30.]
[10 40 90]
[ -9 -18 -27]

In [14]:
x = np.arange(4)
print(x)
print(x.shape)

[0 1 2 3]
(4,)

In [15]:
xx = x.reshape(4,1)  #*****
print(xx)

[[0]
 [1]
 [2]
 [3]]

In [16]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [17]:
random = np.random.random((3,3))
print(random)

[[0.34324641 0.01954651 0.23500525]
 [0.4597541  0.94105741 0.70314481]
 [0.28643307 0.76074225 0.78775162]]



> Indented block



# Python for Data List

In [18]:
fruits = ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi"]

print(fruits)
print(fruits[0:5])

['pineapple', 'apple', 'lemon', 'strawberry', 'orange', 'kiwi']
['pineapple', 'apple', 'lemon', 'strawberry', 'orange']

In [19]:
fruits.append("peach")
fruits # ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi", "peach"]

['pineapple', 'apple', 'lemon', 'strawberry', 'orange', 'kiwi', 'peach']

In [20]:
fruits[0:2] = ["grape", "mango"]
fruits # ["grape", "mango", "lemon", "strawberry", "orange", "kiwi", "peach", "fig", "melon"]

['grape', 'mango', 'lemon', 'strawberry', 'orange', 'kiwi', 'peach']

In [21]:
fruits.remove("mango")
fruits # ["grape", "lemon", "strawberry", "orange", "kiwi", "peach", "fig", "melon"]

['grape', 'lemon', 'strawberry', 'orange', 'kiwi', 'peach']

In [22]:
movies = ["Iron Man", "Bat Man", "Spider Man"]
ratings = [7.7, 8.1, 6.8]
print(movies[0],ratings[0])
#movie_choice_index = movies.index("Bat Man")
print(ratings[movies.index("Spider Man")])

Iron Man 7.7
6.8

In [23]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful


# Python for Data Dictionary

In [24]:
#Key , Value
ratings = {
    "American Standard": 3.4,
    "Ex Machina": 7.7,
    "Mad Max: Fury Road": 8.1,
    "1408" : 6.8
}

ratings["Ex Machina"]
print(ratings)

{'American Standard': 3.4, 'Ex Machina': 7.7, 'Mad Max: Fury Road': 8.1, '1408': 6.8}

In [25]:
ratings

#Add new value
ratings['1408'] = 9.9
ratings["Deadpool"] = 8.0
#delete value
del(ratings["1408"])

ratings

{'American Standard': 3.4,
 'Ex Machina': 7.7,
 'Mad Max: Fury Road': 8.1,
 'Deadpool': 8.0}

In [26]:
def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    current_number = 5
    while current_number * current_number <= n:
        if n % current_number == 0 or n % (current_number + 2) == 0:
            return False
        current_number = current_number + 6
    return True


is_prime(7)

True

Pandas คือ ...

# Pandas in Python

The primary data structures in pandas are implemented as two classes:


*   DataFrame, which you can imagine as a relational data table, with rows and named columns.
*   Series, which is a single column. A DataFrame contains one or more Series and a name for each Series.

In [27]:
import pandas as pd
df = pd.DataFrame(
    {
    "Name": [
             "Somchai",
             "Somying",
             "Somjai",
             ],
    "Age": [22, 35, 58],
    "Sex": ["male", "male", "female"],
    }
)

print(df)

      Name  Age     Sex
0  Somchai   22    male
1  Somying   35    male
2   Somjai   58  female

In [ ]:
print(df.loc[0])

In [ ]:
print(df[0:3])

In [ ]:
print(df.loc[0:1])

In [ ]:
print(df.loc[2])

In [ ]:
print(df.iloc[2])

#Example #1

In [28]:
import pandas as pd
true_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/01418496/data/True_news.csv')
fake_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/01418496/data/Fake_news.csv')
print(true_df.head(10))
print(fake_df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/01418496/data/True_news.csv'

In [ ]:
true_df['check'] = 'TRUE'
fake_df['check'] = 'FAKE'
print(true_df.head())
print(fake_df.head())

In [ ]:
#Concatenate
df_news = pd.concat([true_df,fake_df])
print(df_news.describe())
print(df_news.head(10))

In [ ]:
#Column selection
print(df_news['subject'])

In [ ]:
print(df_news[['subject','date']])

In [ ]:
print(df_news.iloc[2000:2125, 2:6])

# WorkShop   (Download Data from URL)

In [30]:
import requests

download_url = "https://media.geeksforgeeks.org/wp-content/uploads/employees.csv"
target_csv_path = "all_testdata.csv"

response = requests.get(download_url)
response.raise_for_status()    # Check that the request was successful
with open(target_csv_path, "wb") as f:
    f.write(response.content)
print("Download ready.")

Download ready.

ทำการอ่านไฟล์ที่ Downaload

In [29]:
employee = pd.read_csv("all_testdata.csv")
len(employee)
employee.shape

(1000, 8)

ทำการแสดงข้อมูลทั้งหมด

In [31]:
employee

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

ทำการสำรวจข้อมูลที่ download มา ด้วยการ count จำนวน

In [32]:
employee.count()

First Name            933
Gender                855
Start Date           1000
Last Login Time      1000
Salary               1000
Bonus %              1000
Senior Management     933
Team                  957
dtype: int64

ทำการสร้าง DataFrame

In [34]:
df_employee = pd.DataFrame(employee)

ดึงข้อมูลชื่อ และเงินเดือน

In [35]:
df_employee[["First Name","Salary"]]

    First Name  Salary
0      Douglas   97308
1       Thomas   61933
2        Maria  130590
3        Jerry  138705
4        Larry  101004
..         ...     ...
995      Henry  132483
996    Phillip   42392
997    Russell   96914
998      Larry   60500
999     Albert  129949

[1000 rows x 2 columns]

ดึงข้อมูลของพนักงานคนที่ 5 ถึงคนที่ 10

In [36]:
df_employee[5:11]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN

ข้อมูลของพนักงานที่ได้เงินเดือนเกิน 10000

In [37]:
df_employee[df_employee["Salary"] > 10000]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

ดึงข้อมูลของพนักงานที่อยู่ใน ทีม Finance กับ Sales

In [38]:
df_employee.query("Team == 'Finance' or Team == 'Sales'")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
...,...,...,...,...,...,...,...,...
975,Susan,Female,4/7/1995,10:05 PM,92436,12.467,False,Sales
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

ดึงข้อมูลชื่อของคนที่ได้เงินเดือนมากกว่า 100000

In [39]:
df_employee[df_employee["Salary"] > 100000]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
990,Robin,Female,7/24/1987,1:35 PM,100765,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales